// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qwewr.Models
{
    public partial class KapchaTable
    {
        public string Capcha { get; set; }
        public string Text { get; set; }
    }
}